language: php
php:
  - 5.5
  - 5.6
  - 7

install:
  - phpize -v
  - composer selfupdate
  - composer install --prefer-source
  - cd ./vendor/phalcon/zephir/
  - ./unit-tests/ci/before_install.sh
  - export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LD_LIBRARY_PATH
  - export LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LIBRARY_PATH
  - export C_INCLUDE_PATH="$TRAVIS_BUILD_DIR/build/include"
  - ./install-nosudo -c
  - cd ./../../../

before_script:
  - mkdir -p converted/Symfony
  - mv config.json converted/Symfony/config.json
  - mv vendor/symfony/event-dispatcher/phpunit.xml.dist converted/Symfony/phpunit.xml
  - mv vendor/symfony/event-dispatcher/Tests converted/Symfony/Tests
  - mv vendor/symfony/event-dispatcher/composer.json converted/Symfony/composer.json
  - composer update

script:
  - vendor/bin/php-to-zephir phpToZephir:convert vendor/symfony/event-dispatcher/
  - cd vendor/symfony/event-dispatcher/
  - composer require phalcon/zephir:0.8.*
  - vendor/bin/zephir build
  - php -dextension=symfony.so ./vendor/bin/phpunit

after_failure:
  - cat compile-errors.log

