language: php
php:
  - 5.5
  - 5.6

install:
  - phpize -v
  - composer selfupdate
  - composer install --prefer-source
  - cd ./vendor/phalcon/zephir/
  - ./unit-tests/ci/before_install.sh
  - export LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LD_LIBRARY_PATH
  - export LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LIBRARY_PATH
  - export C_INCLUDE_PATH="$TRAVIS_BUILD_DIR/build/include"
  - ./install-nosudo -c
  - cd ./../../../

before_script:
  - mv vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/phpunit.xml.dist phpunit.xml
  - mv vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/Tests Tests
  - vendor/bin/php-to-zephir phpToZephir:convertDir vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher
  - vendor/bin/zephir build

script: php -dextension=symfony.so ./vendor/bin/phpunit

